services:
  - type: web
    name: guessify-server
    env: node
    plan: free
    branch: main
    buildCommand: npm install; npm --prefix ./client install; npm --prefix ./client run build; npm --prefix ./server install
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
