services:
  - type: web
    name: guessify-server
    env: node
    plan: free
    branch: main
    buildCommand: npm --prefix server install
    startCommand: npm --prefix server start
    envVars:
      - key: NODE_ENV
        value: production
