services:
  - type: web
    name: guessify-server
    env: node
    plan: free
    branch: main
    buildCommand: npm ci --prefix server
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
