services:
  - type: web
    name: guessify-server
    env: node
    plan: free
    branch: main
    buildCommand: npm install && cd client && npm install && npm run build && cd ../server && npm install
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
